<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

class DistrictsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('districts')->insert([
                        // Hà Nội (id_province = 1)
                        ['id_district' => 1, 'name' => 'Ba Đình', 'id_province' => 1],
                        ['id_district' => 2, 'name' => 'Hoàn Kiếm', 'id_province' => 1],
                        ['id_district' => 3, 'name' => 'Tây Hồ', 'id_province' => 1],
                        ['id_district' => 4, 'name' => 'Long Biên', 'id_province' => 1],
                        ['id_district' => 5, 'name' => 'Cầu Giấy', 'id_province' => 1],
                        ['id_district' => 6, 'name' => 'Đống Đa', 'id_province' => 1],
                        ['id_district' => 7, 'name' => 'Hai Bà Trưng', 'id_province' => 1],
                        ['id_district' => 8, 'name' => 'Hoàng Mai', 'id_province' => 1],
                        ['id_district' => 9, 'name' => 'Thanh Xuân', 'id_province' => 1],
                        ['id_district' => 10, 'name' => 'Sóc Sơn', 'id_province' => 1],
                        ['id_district' => 11, 'name' => 'Đông Anh', 'id_province' => 1],
                        ['id_district' => 12, 'name' => 'Gia Lâm', 'id_province' => 1],
                        ['id_district' => 13, 'name' => 'Nam Từ Liêm', 'id_province' => 1],
                        ['id_district' => 14, 'name' => 'Thanh Trì', 'id_province' => 1],
                        ['id_district' => 15, 'name' => 'Bắc Từ Liêm', 'id_province' => 1],
                        ['id_district' => 16, 'name' => 'Mê Linh', 'id_province' => 1],
                        ['id_district' => 17, 'name' => 'Hà Đông', 'id_province' => 1],
                        ['id_district' => 18, 'name' => 'Sơn Tây', 'id_province' => 1],
                        ['id_district' => 19, 'name' => 'Ba Vì', 'id_province' => 1],
                        ['id_district' => 20, 'name' => 'Phúc Thọ', 'id_province' => 1],
                        ['id_district' => 21, 'name' => 'Đan Phượng', 'id_province' => 1],
                        ['id_district' => 22, 'name' => 'Hoài Đức', 'id_province' => 1],
                        ['id_district' => 23, 'name' => 'Quốc Oai', 'id_province' => 1],
                        ['id_district' => 24, 'name' => 'Thạch Thất', 'id_province' => 1],
                        ['id_district' => 25, 'name' => 'Chương Mỹ', 'id_province' => 1],
                        ['id_district' => 26, 'name' => 'Thanh Oai', 'id_province' => 1],
                        ['id_district' => 27, 'name' => 'Thường Tín', 'id_province' => 1],
                        ['id_district' => 28, 'name' => 'Phú Xuyên', 'id_province' => 1],
                        ['id_district' => 29, 'name' => 'Ứng Hòa', 'id_province' => 1],
                        ['id_district' => 30, 'name' => 'Mỹ Đức', 'id_province' => 1],
            
                        // TP.HCM (id_province = 2)
                        ['id_district' => 31, 'name' => '1', 'id_province' => 2],
                        ['id_district' => 32, 'name' => '12', 'id_province' => 2],
                        ['id_district' => 33, 'name' => 'Thủ Đức', 'id_province' => 2],
                        ['id_district' => 34, 'name' => 'Gò Vấp', 'id_province' => 2],
                        ['id_district' => 35, 'name' => 'Bình Thạnh', 'id_province' => 2],
                        ['id_district' => 36, 'name' => 'Tân Bình', 'id_province' => 2],
                        ['id_district' => 37, 'name' => 'Tân Phú', 'id_province' => 2],
                        ['id_district' => 38, 'name' => 'Phú Nhuận', 'id_province' => 2],
                        ['id_district' => 40, 'name' => '3', 'id_province' => 2],
                        ['id_district' => 41, 'name' => '10', 'id_province' => 2],
                        ['id_district' => 42, 'name' => '11', 'id_province' => 2],
                        ['id_district' => 43, 'name' => '4', 'id_province' => 2],
                        ['id_district' => 44, 'name' => '5', 'id_province' => 2],
                        ['id_district' => 45, 'name' => '6', 'id_province' => 2],
                        ['id_district' => 46, 'name' => '8', 'id_province' => 2],
                        ['id_district' => 47, 'name' => 'Bình Tân', 'id_province' => 2],
                        ['id_district' => 48, 'name' => '7', 'id_province' => 2],
                        ['id_district' => 49, 'name' => 'Củ Chi', 'id_province' => 2],
                        ['id_district' => 50, 'name' => 'Hóc Môn', 'id_province' => 2],
                        ['id_district' => 51, 'name' => 'Bình Chánh', 'id_province' => 2],
                        ['id_district' => 52, 'name' => 'Nhà Bè', 'id_province' => 2],
                        ['id_district' => 53, 'name' => 'Cần Giờ', 'id_province' => 2],
                        ['id_district' => 54, 'name' => 'Hải Châu', 'id_province' => 3],
                        ['id_district' => 55, 'name' => 'Thanh Khê', 'id_province' => 3],
                        ['id_district' => 56, 'name' => 'Sơn Trà', 'id_province' => 3],
                        ['id_district' => 57, 'name' => 'Ngũ Hành Sơn', 'id_province' => 3],
                        ['id_district' => 58, 'name' => 'Liên Chiểu', 'id_province' => 3],
                        ['id_district' => 59, 'name' => 'Cẩm Lệ', 'id_province' => 3],
                        ['id_district' => 60, 'name' => 'Hòa Vang', 'id_province' => 3],
                        ['id_district' => 61, 'name' => 'Hoàng Sa', 'id_province' => 3],
            
                        // Hải Phòng
                        ['id_district' => 62, 'name' => 'Hồng Bàng', 'id_province' => 4],
                        ['id_district' => 63, 'name' => 'Ngô Quyền', 'id_province' => 4],
                        ['id_district' => 64, 'name' => 'Lê Chân', 'id_province' => 4],
                        ['id_district' => 65, 'name' => 'Hải An', 'id_province' => 4],
                        ['id_district' => 66, 'name' => 'Kiến An', 'id_province' => 4],
                        ['id_district' => 67, 'name' => 'Đồ Sơn', 'id_province' => 4],
                        ['id_district' => 68, 'name' => 'Dương Kinh', 'id_province' => 4],
                        ['id_district' => 69, 'name' => 'Thủy Nguyên', 'id_province' => 4],
                        ['id_district' => 70, 'name' => 'An Dương', 'id_province' => 4],
                        ['id_district' => 71, 'name' => 'An Lão', 'id_province' => 4],
                        ['id_district' => 72, 'name' => 'Kiến Thụy', 'id_province' => 4],
                        ['id_district' => 73, 'name' => 'Tiên Lãng', 'id_province' => 4],
                        ['id_district' => 74, 'name' => 'Vĩnh Bảo', 'id_province' => 4],
                        ['id_district' => 75, 'name' => 'Cát Hải', 'id_province' => 4],
                        ['id_district' => 76, 'name' => 'Bạch Long Vĩ', 'id_province' => 4],
            
                        // Cần Thơ
                        ['id_district' => 77, 'name' => 'Ninh Kiều', 'id_province' => 5],
                        ['id_district' => 78, 'name' => 'Ô Môn', 'id_province' => 5],
                        ['id_district' => 79, 'name' => 'Bình Thủy', 'id_province' => 5],
                        ['id_district' => 80, 'name' => 'Cái Răng', 'id_province' => 5],
                        ['id_district' => 81, 'name' => 'Thốt Nốt', 'id_province' => 5],
                        ['id_district' => 82, 'name' => 'Vĩnh Thạnh', 'id_province' => 5],
                        ['id_district' => 83, 'name' => 'Cờ Đỏ', 'id_province' => 5],
                        ['id_district' => 84, 'name' => 'Phong Điền', 'id_province' => 5],
                        ['id_district' => 85, 'name' => 'Thới Lai', 'id_province' => 5],
            
                        // An Giang
                        ['id_district' => 86, 'name' => 'Long Xuyên', 'id_province' => 6],
                        ['id_district' => 87, 'name' => 'Châu Đốc', 'id_province' => 6],
                        ['id_district' => 88, 'name' => 'An Phú', 'id_province' => 6],
                        ['id_district' => 89, 'name' => 'Tân Châu', 'id_province' => 6],
                        ['id_district' => 90, 'name' => 'Phú Tân', 'id_province' => 6],
                        ['id_district' => 91, 'name' => 'Châu Phú', 'id_province' => 6],
                        ['id_district' => 92, 'name' => 'Tịnh Biên', 'id_province' => 6],
                        ['id_district' => 93, 'name' => 'Tri Tôn', 'id_province' => 6],
                        ['id_district' => 94, 'name' => 'Châu Thành', 'id_province' => 6],
                        ['id_district' => 95, 'name' => 'Chợ Mới', 'id_province' => 6],
                        ['id_district' => 96, 'name' => 'Thoại Sơn', 'id_province' => 6],

                        // Hà Giang
                        ['id_district' => 97, 'name' => 'Hà Giang', 'id_province' => 25],
                        ['id_district' => 98, 'name' => 'Đồng Văn', 'id_province' => 25],
                        ['id_district' => 99, 'name' => 'Mèo Vạc', 'id_province' => 25],
                        ['id_district' => 100, 'name' => 'Yên Minh', 'id_province' => 25],
                        ['id_district' => 101, 'name' => 'Quản Bạ', 'id_province' => 25],
                        ['id_district' => 102, 'name' => 'Vị Xuyên', 'id_province' => 25],
                        ['id_district' => 103, 'name' => 'Bắc Mê', 'id_province' => 25],
                        ['id_district' => 104, 'name' => 'Hoàng Su Phì', 'id_province' => 25],
                        ['id_district' => 105, 'name' => 'Xín Mần', 'id_province' => 25],
                        ['id_district' => 106, 'name' => 'Bắc Quang', 'id_province' => 25],
                        ['id_district' => 107, 'name' => 'Quang Bình', 'id_province' => 25],

                        // Nghệ An
                        ['id_district' => 108, 'name' => 'Vinh', 'id_province' => 41],
                        ['id_district' => 109, 'name' => 'Cửa Lò', 'id_province' => 41],
                        ['id_district' => 110, 'name' => 'Thái Hòa', 'id_province' => 41],
                        ['id_district' => 111, 'name' => 'Quế Phong', 'id_province' => 41],
                        ['id_district' => 112, 'name' => 'Quỳ Châu', 'id_province' => 41],
                        ['id_district' => 113, 'name' => 'Kỳ Sơn', 'id_province' => 41],
                        ['id_district' => 114, 'name' => 'Tương Dương', 'id_province' => 41],
                        ['id_district' => 115, 'name' => 'Nghĩa Đàn', 'id_province' => 41],
                        ['id_district' => 116, 'name' => 'Quỳ Hợp', 'id_province' => 41],
                        ['id_district' => 117, 'name' => 'Quỳnh Lưu', 'id_province' => 41],
                        ['id_district' => 118, 'name' => 'Con Cuông', 'id_province' => 41],
                        ['id_district' => 119, 'name' => 'Tân Kỳ', 'id_province' => 41],
                        ['id_district' => 120, 'name' => 'Anh Sơn', 'id_province' => 41],
                        ['id_district' => 121, 'name' => 'Diễn Châu', 'id_province' => 41],
                        ['id_district' => 122, 'name' => 'Yên Thành', 'id_province' => 41],
                        ['id_district' => 123, 'name' => 'Đô Lương', 'id_province' => 41],
                        ['id_district' => 124, 'name' => 'Thanh Chương', 'id_province' => 41],
                        ['id_district' => 125, 'name' => 'Nghi Lộc', 'id_province' => 41],
                        ['id_district' => 126, 'name' => 'Nam Đàn', 'id_province' => 41],
                        ['id_district' => 127, 'name' => 'Hưng Nguyên', 'id_province' => 41],

                        // Thanh Hóa
                        ['id_district' => 128, 'name' => 'Thanh Hóa', 'id_province' => 55],
                        ['id_district' => 129, 'name' => 'Bỉm Sơn', 'id_province' => 55],
                        ['id_district' => 130, 'name' => 'Sầm Sơn', 'id_province' => 55],
                        ['id_district' => 131, 'name' => 'Mường Lát', 'id_province' => 55],
                        ['id_district' => 132, 'name' => 'Quan Hóa', 'id_province' => 55],
                        ['id_district' => 133, 'name' => 'Bá Thước', 'id_province' => 55],
                        ['id_district' => 134, 'name' => 'Quan Sơn', 'id_province' => 55],
                        ['id_district' => 135, 'name' => 'Lang Chánh', 'id_province' => 55],
                        ['id_district' => 136, 'name' => 'Ngọc Lặc', 'id_province' => 55],
                        ['id_district' => 137, 'name' => 'Cẩm Thủy', 'id_province' => 55],
                        ['id_district' => 138, 'name' => 'Thạch Thành', 'id_province' => 55],
                        ['id_district' => 139, 'name' => 'Hà Trung', 'id_province' => 55],
                        ['id_district' => 140, 'name' => 'Vĩnh Lộc', 'id_province' => 55],
                        ['id_district' => 141, 'name' => 'Yên Định', 'id_province' => 55],
                        ['id_district' => 142, 'name' => 'Thọ Xuân', 'id_province' => 55],
                        ['id_district' => 143, 'name' => 'Thường Xuân', 'id_province' => 55],
                        ['id_district' => 144, 'name' => 'Triệu Sơn', 'id_province' => 55],
                        ['id_district' => 145, 'name' => 'Thiệu Hóa', 'id_province' => 55],
                        ['id_district' => 146, 'name' => 'Hoằng Hóa', 'id_province' => 55],
                        ['id_district' => 147, 'name' => 'Hậu Lộc', 'id_province' => 55],
                        ['id_district' => 148, 'name' => 'Nga Sơn', 'id_province' => 55],
                        ['id_district' => 149, 'name' => 'Như Xuân', 'id_province' => 55],
                        ['id_district' => 150, 'name' => 'Như Thanh', 'id_province' => 55],
                        ['id_district' => 151, 'name' => 'Nông Cống', 'id_province' => 55],
                        ['id_district' => 152, 'name' => 'Đông Sơn', 'id_province' => 55],
                        ['id_district' => 153, 'name' => 'Quảng Xương', 'id_province' => 55],
                        ['id_district' => 154, 'name' => 'Tĩnh Gia', 'id_province' => 55],

                                    // Bắc Giang
                        ['id_district' => 155, 'name' => 'Bắc Giang', 'id_province' => 8],
                        ['id_district' => 156, 'name' => 'Yên Thế', 'id_province' => 8],
                        ['id_district' => 157, 'name' => 'Tân Yên', 'id_province' => 8],
                        ['id_district' => 158, 'name' => 'Lạng Giang', 'id_province' => 8],
                        ['id_district' => 159, 'name' => 'Lục Nam', 'id_province' => 8],
                        ['id_district' => 160, 'name' => 'Lục Ngạn', 'id_province' => 8],
                        ['id_district' => 161, 'name' => 'Sơn Động', 'id_province' => 8],
                        ['id_district' => 162, 'name' => 'Yên Dũng', 'id_province' => 8],
                        ['id_district' => 163, 'name' => 'Việt Yên', 'id_province' => 8],
                        ['id_district' => 164, 'name' => 'Hiệp Hòa', 'id_province' => 8],

                        // Bắc Kạn
                        ['id_district' => 165, 'name' => 'Bắc Kạn', 'id_province' => 9],
                        ['id_district' => 166, 'name' => 'Pác Nặm', 'id_province' => 9],
                        ['id_district' => 167, 'name' => 'Ba Bể', 'id_province' => 9],
                        ['id_district' => 168, 'name' => 'Ngân Sơn', 'id_province' => 9],
                        ['id_district' => 169, 'name' => 'Bạch Thông', 'id_province' => 9],
                        ['id_district' => 170, 'name' => 'Chợ Đồn', 'id_province' => 9],
                        ['id_district' => 171, 'name' => 'Chợ Mới', 'id_province' => 9],
                        ['id_district' => 172, 'name' => 'Na Rì', 'id_province' => 9],

                        // Bạc Liêu
                        ['id_district' => 173, 'name' => 'Bạc Liêu', 'id_province' => 10],
                        ['id_district' => 174, 'name' => 'Hồng Dân', 'id_province' => 10],
                        ['id_district' => 175, 'name' => 'Phước Long', 'id_province' => 10],
                        ['id_district' => 176, 'name' => 'Vĩnh Lợi', 'id_province' => 10],
                        ['id_district' => 177, 'name' => 'Giá Rai', 'id_province' => 10],
                        ['id_district' => 178, 'name' => 'Đông Hải', 'id_province' => 10],
                        ['id_district' => 179, 'name' => 'Hòa Bình', 'id_province' => 10],

                        // Bắc Ninh
                        ['id_district' => 180, 'name' => 'Bắc Ninh', 'id_province' => 11],
                        ['id_district' => 181, 'name' => 'Yên Phong', 'id_province' => 11],
                        ['id_district' => 182, 'name' => 'Quế Võ', 'id_province' => 11],
                        ['id_district' => 183, 'name' => 'Tiên Du', 'id_province' => 11],
                        ['id_district' => 184, 'name' => 'Từ Sơn', 'id_province' => 11],
                        ['id_district' => 185, 'name' => 'Thuận Thành', 'id_province' => 11],
                        ['id_district' => 186, 'name' => 'Gia Bình', 'id_province' => 11],
                        ['id_district' => 187, 'name' => 'Lương Tài', 'id_province' => 11],

                        // Bến Tre
                        ['id_district' => 188, 'name' => 'Bến Tre', 'id_province' => 12],
                        ['id_district' => 189, 'name' => 'Châu Thành', 'id_province' => 12],
                        ['id_district' => 190, 'name' => 'Chợ Lách', 'id_province' => 12],
                        ['id_district' => 191, 'name' => 'Mỏ Cày Bắc', 'id_province' => 12],
                        ['id_district' => 192, 'name' => 'Mỏ Cày Nam', 'id_province' => 12],
                        ['id_district' => 193, 'name' => 'Giồng Trôm', 'id_province' => 12],
                        ['id_district' => 194, 'name' => 'Bình Đại', 'id_province' => 12],
                        ['id_district' => 195, 'name' => 'Ba Tri', 'id_province' => 12],
                        ['id_district' => 196, 'name' => 'Thạnh Phú', 'id_province' => 12],

                        // Bình Định
                        ['id_district' => 197, 'name' => 'Quy Nhơn', 'id_province' => 13],
                        ['id_district' => 198, 'name' => 'An Lão', 'id_province' => 13],
                        ['id_district' => 199, 'name' => 'Hoài Ân', 'id_province' => 13],
                        ['id_district' => 200, 'name' => 'Hoài Nhơn', 'id_province' => 13],
                        ['id_district' => 201, 'name' => 'Phù Mỹ', 'id_province' => 13],
                        ['id_district' => 202, 'name' => 'Phù Cát', 'id_province' => 13],
                        ['id_district' => 203, 'name' => 'Vĩnh Thạnh', 'id_province' => 13],
                        ['id_district' => 204, 'name' => 'Tây Sơn', 'id_province' => 13],
                        ['id_district' => 205, 'name' => 'Vân Canh', 'id_province' => 13],
                        ['id_district' => 206, 'name' => 'An Nhơn', 'id_province' => 13],
                        ['id_district' => 207, 'name' => 'Tuy Phước', 'id_province' => 13],

                        // Bình Dương
                        ['id_district' => 208, 'name' => 'Thủ Dầu Một', 'id_province' => 14],
                        ['id_district' => 209, 'name' => 'Bến Cát', 'id_province' => 14],
                        ['id_district' => 210, 'name' => 'Tân Uyên', 'id_province' => 14],
                        ['id_district' => 211, 'name' => 'Dĩ An', 'id_province' => 14],
                        ['id_district' => 212, 'name' => 'Thuận An', 'id_province' => 14],
                        ['id_district' => 213, 'name' => 'Phú Giáo', 'id_province' => 14],
                        ['id_district' => 214, 'name' => 'Bắc Tân Uyên', 'id_province' => 14],
                        ['id_district' => 215, 'name' => 'Bàu Bàng', 'id_province' => 14],
                        ['id_district' => 216, 'name' => 'Dầu Tiếng', 'id_province' => 14],

                        // Bình Phước
                        ['id_district' => 217, 'name' => 'Đồng Xoài', 'id_province' => 15],
                        ['id_district' => 218, 'name' => 'Phước Long', 'id_province' => 15],
                        ['id_district' => 219, 'name' => 'Bình Long', 'id_province' => 15],
                        ['id_district' => 220, 'name' => 'Bù Đăng', 'id_province' => 15],
                        ['id_district' => 221, 'name' => 'Bù Đốp', 'id_province' => 15],
                        ['id_district' => 222, 'name' => 'Bù Gia Mập', 'id_province' => 15],
                        ['id_district' => 223, 'name' => 'Chơn Thành', 'id_province' => 15],
                        ['id_district' => 224, 'name' => 'Đồng Phú', 'id_province' => 15],
                        ['id_district' => 225, 'name' => 'Hớn Quản', 'id_province' => 15],
                        ['id_district' => 226, 'name' => 'Lộc Ninh', 'id_province' => 15],
                        ['id_district' => 227, 'name' => 'Phú Riềng', 'id_province' => 15],

                        // Bình Thuận
                        ['id_district' => 228, 'name' => 'Phan Thiết', 'id_province' => 16],
                        ['id_district' => 229, 'name' => 'La Gi', 'id_province' => 16],
                        ['id_district' => 230, 'name' => 'Bắc Bình', 'id_province' => 16],
                        ['id_district' => 231, 'name' => 'Đức Linh', 'id_province' => 16],
                        ['id_district' => 232, 'name' => 'Hàm Tân', 'id_province' => 16],
                        ['id_district' => 233, 'name' => 'Hàm Thuận Bắc', 'id_province' => 16],
                        ['id_district' => 234, 'name' => 'Hàm Thuận Nam', 'id_province' => 16],
                        ['id_district' => 235, 'name' => 'Phú Quý', 'id_province' => 16],
                        ['id_district' => 236, 'name' => 'Tánh Linh', 'id_province' => 16],
                        ['id_district' => 237, 'name' => 'Tuy Phong', 'id_province' => 16],

                        // Cà Mau
                        ['id_district' => 238, 'name' => 'Cà Mau', 'id_province' => 17],
                        ['id_district' => 239, 'name' => 'Cái Nước', 'id_province' => 17],
                        ['id_district' => 240, 'name' => 'Đầm Dơi', 'id_province' => 17],
                        ['id_district' => 241, 'name' => 'Năm Căn', 'id_province' => 17],
                        ['id_district' => 242, 'name' => 'Ngọc Hiển', 'id_province' => 17],
                        ['id_district' => 243, 'name' => 'Phú Tân', 'id_province' => 17],
                        ['id_district' => 244, 'name' => 'Thới Bình', 'id_province' => 17],
                        ['id_district' => 245, 'name' => 'Trần Văn Thời', 'id_province' => 17],
                        ['id_district' => 246, 'name' => 'U Minh', 'id_province' => 17],

                        // Cao Bằng
                        ['id_district' => 247, 'name' => 'Cao Bằng', 'id_province' => 18],
                        ['id_district' => 248, 'name' => 'Bảo Lạc', 'id_province' => 18],
                        ['id_district' => 249, 'name' => 'Bảo Lâm', 'id_province' => 18],
                        ['id_district' => 250, 'name' => 'Hạ Lang', 'id_province' => 18],
                        ['id_district' => 251, 'name' => 'Hà Quảng', 'id_province' => 18],
                        ['id_district' => 252, 'name' => 'Hòa An', 'id_province' => 18],
                        ['id_district' => 253, 'name' => 'Nguyên Bình', 'id_province' => 18],
                        ['id_district' => 254, 'name' => 'Phục Hòa', 'id_province' => 18],
                        ['id_district' => 256, 'name' => 'Thạch An', 'id_province' => 18],
                        ['id_district' => 258, 'name' => 'Trùng Khánh', 'id_province' => 18],

                        // Đắk Lắk
                        ['id_district' => 259, 'name' => 'Buôn Ma Thuột', 'id_province' => 19],
                        ['id_district' => 260, 'name' => 'Buôn Đôn', 'id_province' => 19],
                        ['id_district' => 261, 'name' => 'Cư Kuin', 'id_province' => 19],
                        ['id_district' => 262, 'name' => 'Cư Mgar', 'id_province' => 19],
                        ['id_district' => 263, 'name' => 'Ea Hleo', 'id_province' => 19],
                        ['id_district' => 264, 'name' => 'Ea Kar', 'id_province' => 19],
                        ['id_district' => 265, 'name' => 'Ea Súp', 'id_province' => 19],
                        ['id_district' => 266, 'name' => 'Krông Ana', 'id_province' => 19],
                        ['id_district' => 267, 'name' => 'Krông Bông', 'id_province' => 19],
                        ['id_district' => 268, 'name' => 'Krông Buk', 'id_province' => 19],
                        ['id_district' => 269, 'name' => 'Krông Năng', 'id_province' => 19],
                        ['id_district' => 270, 'name' => 'Krông Pắc', 'id_province' => 19],
                        ['id_district' => 271, 'name' => 'Lắk', 'id_province' => 19],
                        ['id_district' => 272, 'name' => "M\Drăk", 'id_province' => 19],
                        
                        // Đắk Nông
                        ['id_district' => 273, 'name' => 'Gia Nghĩa', 'id_province' => 20],
                        ['id_district' => 274, 'name' => 'Cư Jút', 'id_province' => 20],
                        ['id_district' => 275, 'name' => 'Đắk Glong', 'id_province' => 20],
                        ['id_district' => 276, 'name' => 'Đắk Mil', 'id_province' => 20],
                        ['id_district' => 277, 'name' => "Đắk R'Lấp", 'id_province' => 20],
                        ['id_district' => 278, 'name' => 'Đắk Song', 'id_province' => 20],
                        ['id_district' => 279, 'name' => 'Krông Nô', 'id_province' => 20],
                        ['id_district' => 280, 'name' => 'Tuy Đức', 'id_province' => 20],

                        // Điện Biên
                        ['id_district' => 281, 'name' => 'Điện Biên Phủ', 'id_province' => 21],
                        ['id_district' => 282, 'name' => 'Điện Biên', 'id_province' => 21],
                        ['id_district' => 283, 'name' => 'Mường Ảng', 'id_province' => 21],
                        ['id_district' => 284, 'name' => 'Mường Chà', 'id_province' => 21],
                        ['id_district' => 285, 'name' => 'Mường Lay', 'id_province' => 21],
                        ['id_district' => 286, 'name' => 'Mường Nhé', 'id_province' => 21],
                        ['id_district' => 287, 'name' => 'Nậm Pồ', 'id_province' => 21],
                        ['id_district' => 288, 'name' => 'Tủa Chùa', 'id_province' => 21],
                        ['id_district' => 289, 'name' => 'Tuần Giáo', 'id_province' => 21],

                        // Đồng Nai
                        ['id_district' => 290, 'name' => 'Biên Hòa', 'id_province' => 22],
                        ['id_district' => 291, 'name' => 'Long Khánh', 'id_province' => 22],
                        ['id_district' => 292, 'name' => 'Cẩm Mỹ', 'id_province' => 22],
                        ['id_district' => 293, 'name' => 'Định Quán', 'id_province' => 22],
                        ['id_district' => 294, 'name' => 'Long Thành', 'id_province' => 22],
                        ['id_district' => 295, 'name' => 'Nhơn Trạch', 'id_province' => 22],
                        ['id_district' => 296, 'name' => 'Tân Phú', 'id_province' => 22],
                        ['id_district' => 297, 'name' => 'Thống Nhất', 'id_province' => 22],
                        ['id_district' => 298, 'name' => 'Trảng Bom', 'id_province' => 22],
                        ['id_district' => 299, 'name' => 'Vĩnh Cửu', 'id_province' => 22],
                        ['id_district' => 300, 'name' => 'Xuân Lộc', 'id_province' => 22],

                        // Đồng Tháp
                        ['id_district' => 301, 'name' => 'Cao Lãnh', 'id_province' => 23],
                        ['id_district' => 302, 'name' => 'Hồng Ngự', 'id_province' => 23],
                        ['id_district' => 303, 'name' => 'Lai Vung', 'id_province' => 23],
                        ['id_district' => 304, 'name' => 'Lấp Vò', 'id_province' => 23],
                        ['id_district' => 305, 'name' => 'Tam Nông', 'id_province' => 23],
                        ['id_district' => 306, 'name' => 'Tân Hồng', 'id_province' => 23],
                        ['id_district' => 307, 'name' => 'Thanh Bình', 'id_province' => 23],
                        ['id_district' => 308, 'name' => 'Tháp Mười', 'id_province' => 23],
                        ['id_district' => 309, 'name' => 'Châu Thành', 'id_province' => 23],

                        // Gia Lai
                        ['id_district' => 310, 'name' => 'Pleiku', 'id_province' => 24],
                        ['id_district' => 311, 'name' => 'An Khê', 'id_province' => 24],
                        ['id_district' => 312, 'name' => 'Ayun Pa', 'id_province' => 24],
                        ['id_district' => 313, 'name' => 'Chư Păh', 'id_province' => 24],
                        ['id_district' => 314, 'name' => 'Chư Prông', 'id_province' => 24],
                        ['id_district' => 315, 'name' => 'Chư Sê', 'id_province' => 24],
                        ['id_district' => 316, 'name' => 'Đăk Đoa', 'id_province' => 24],
                        ['id_district' => 317, 'name' => 'Ia Grai', 'id_province' => 24],
                        ['id_district' => 318, 'name' => 'Ia Pa', 'id_province' => 24],
                        ['id_district' => 319, 'name' => 'KBang', 'id_province' => 24],
                        ['id_district' => 320, 'name' => 'Kông Chro', 'id_province' => 24],
                        ['id_district' => 321, 'name' => 'Krông Pa', 'id_province' => 24],
                        ['id_district' => 322, 'name' => 'Mang Yang', 'id_province' => 24],

                        // Hà Nam
                        ['id_district' => 323, 'name' => 'Phủ Lý', 'id_province' => 26],
                        ['id_district' => 324, 'name' => 'Bình Lục', 'id_province' => 26],
                        ['id_district' => 325, 'name' => 'Duy Tiên', 'id_province' => 26],
                        ['id_district' => 326, 'name' => 'Kim Bảng', 'id_province' => 26],
                        ['id_district' => 327, 'name' => 'Lý Nhân', 'id_province' => 26],
                        ['id_district' => 328, 'name' => 'Thanh Liêm', 'id_province' => 26],

                        // Hà Tĩnh
                        ['id_district' => 329, 'name' => 'Hà Tĩnh', 'id_province' => 27],
                        ['id_district' => 330, 'name' => 'Cẩm Xuyên', 'id_province' => 27],
                        ['id_district' => 331, 'name' => 'Can Lộc', 'id_province' => 27],
                        ['id_district' => 332, 'name' => 'Đức Thọ', 'id_province' => 27],
                        ['id_district' => 333, 'name' => 'Hồng Lĩnh', 'id_province' => 27],
                        ['id_district' => 334, 'name' => 'Hương Khê', 'id_province' => 27],
                        ['id_district' => 335, 'name' => 'Hương Sơn', 'id_province' => 27],
                        ['id_district' => 336, 'name' => 'Kỳ Anh', 'id_province' => 27],
                        ['id_district' => 337, 'name' => 'Lộc Hà', 'id_province' => 27],
                        ['id_district' => 338, 'name' => 'Nghi Xuân', 'id_province' => 27],
                        ['id_district' => 339, 'name' => 'Thạch Hà', 'id_province' => 27],
                        ['id_district' => 340, 'name' => 'Vũ Quang', 'id_province' => 27],

                        // Hải Dương
                        ['id_district' => 341, 'name' => 'Hải Dương', 'id_province' => 28],
                        ['id_district' => 342, 'name' => 'Chí Linh', 'id_province' => 28],
                        ['id_district' => 343, 'name' => 'Gia Lộc', 'id_province' => 28],
                        ['id_district' => 344, 'name' => 'Kim Thành', 'id_province' => 28],
                        ['id_district' => 345, 'name' => 'Kinh Môn', 'id_province' => 28],
                        ['id_district' => 346, 'name' => 'Nam Sách', 'id_province' => 28],
                        ['id_district' => 347, 'name' => 'Ninh Giang', 'id_province' => 28],
                        ['id_district' => 348, 'name' => 'Thanh Hà', 'id_province' => 28],
                        ['id_district' => 349, 'name' => 'Thanh Miện', 'id_province' => 28],
            
                        // Hậu Giang
                        ['id_district' => 350, 'name' => 'Vị Thanh', 'id_province' => 29],
                        ['id_district' => 351, 'name' => 'Châu Thành', 'id_province' => 29],
                        ['id_district' => 352, 'name' => 'Châu Thành A', 'id_province' => 29],
                        ['id_district' => 353, 'name' => 'Long Mỹ', 'id_province' => 29],
                        ['id_district' => 354, 'name' => 'Ngã Bảy', 'id_province' => 29],
                        ['id_district' => 355, 'name' => 'Phụng Hiệp', 'id_province' => 29],
            
                        // Hòa Bình
                        ['id_district' => 356, 'name' => 'Hòa Bình', 'id_province' => 30],
                        ['id_district' => 357, 'name' => 'Cao Phong', 'id_province' => 30],
                        ['id_district' => 358, 'name' => 'Đà Bắc', 'id_province' => 30],
                        ['id_district' => 359, 'name' => 'Kim Bôi', 'id_province' => 30],
                        ['id_district' => 361, 'name' => 'Lạc Sơn', 'id_province' => 30],
                        ['id_district' => 362, 'name' => 'Lạc Thủy', 'id_province' => 30],
                        ['id_district' => 363, 'name' => 'Lương Sơn', 'id_province' => 30],
                        ['id_district' => 364, 'name' => 'Mai Châu', 'id_province' => 30],
                        ['id_district' => 365, 'name' => 'Tân Lạc', 'id_province' => 30],
                        ['id_district' => 366, 'name' => 'Yên Thủy', 'id_province' => 30],
            
                        // Hưng Yên
                        ['id_district' => 367, 'name' => 'Hưng Yên', 'id_province' => 31],
                        ['id_district' => 368, 'name' => 'Ân Thi', 'id_province' => 31],
                        ['id_district' => 369, 'name' => 'Khoái Châu', 'id_province' => 31],
                        ['id_district' => 370, 'name' => 'Kim Động', 'id_province' => 31],
                        ['id_district' => 371, 'name' => 'Mỹ Hào', 'id_province' => 31],
                        ['id_district' => 372, 'name' => 'Phù Cừ', 'id_province' => 31],
                        ['id_district' => 373, 'name' => 'Tiên Lữ', 'id_province' => 31],
                        ['id_district' => 374, 'name' => 'Văn Giang', 'id_province' => 31],
                        ['id_district' => 375, 'name' => 'Văn Lâm', 'id_province' => 31],
                        ['id_district' => 376, 'name' => 'Yên Mỹ', 'id_province' => 31],
            
                        // Khánh Hòa
                        ['id_district' => 377, 'name' => 'Nha Trang', 'id_province' => 32],
                        ['id_district' => 378, 'name' => 'Cam Lâm', 'id_province' => 32],
                        ['id_district' => 379, 'name' => 'Cam Ranh', 'id_province' => 32],
                        ['id_district' => 380, 'name' => 'Diên Khánh', 'id_province' => 32],
                        ['id_district' => 381, 'name' => 'Khánh Sơn', 'id_province' => 32],
                        ['id_district' => 382, 'name' => 'Khánh Vĩnh', 'id_province' => 32],
                        ['id_district' => 383, 'name' => 'Ninh Hòa', 'id_province' => 32],
                        ['id_district' => 384, 'name' => 'Trường Sa', 'id_province' => 32],
                        ['id_district' => 385, 'name' => 'Vạn Ninh', 'id_province' => 32],
            
                        // Kiên Giang
                        ['id_district' => 386, 'name' => 'Rạch Giá', 'id_province' => 33],
                        ['id_district' => 387, 'name' => 'An Biên', 'id_province' => 33],
                        ['id_district' => 388, 'name' => 'An Minh', 'id_province' => 33],
                        ['id_district' => 389, 'name' => 'Châu Thành', 'id_province' => 33],
                        ['id_district' => 390, 'name' => 'Giang Thành', 'id_province' => 33],
                        ['id_district' => 391, 'name' => 'Giồng Riềng', 'id_province' => 33],
                        ['id_district' => 392, 'name' => 'Gò Quao', 'id_province' => 33],
                        ['id_district' => 393, 'name' => 'Hòn Đất', 'id_province' => 33],
                        ['id_district' => 394, 'name' => 'Kiên Hải', 'id_province' => 33],
                        ['id_district' => 395, 'name' => 'Kiên Lương', 'id_province' => 33],
                        ['id_district' => 396, 'name' => 'Phú Quốc', 'id_province' => 33],
                        ['id_district' => 397, 'name' => 'Tân Hiệp', 'id_province' => 33],
                        ['id_district' => 398, 'name' => 'U Minh Thượng', 'id_province' => 33],
                        ['id_district' => 399, 'name' => 'Vĩnh Thuận', 'id_province' => 33],
            
                        // Kon Tum
                        ['id_district' => 400, 'name' => 'Kon Tum', 'id_province' => 34],
                        ['id_district' => 401, 'name' => 'Đắk Glei', 'id_province' => 34],
                        ['id_district' => 402, 'name' => 'Đắk Hà', 'id_province' => 34],
                        ['id_district' => 403, 'name' => 'Đắk Tô', 'id_province' => 34],
                        ['id_district' => 404, 'name' => 'Ia HDrai', 'id_province' => 34],
                        ['id_district' => 405, 'name' => 'Kon Plông', 'id_province' => 34],
                        ['id_district' => 406, 'name' => 'Ngọc Hồi', 'id_province' => 34],
                        ['id_district' => 407, 'name' => 'Sa Thầy', 'id_province' => 34],
                        ['id_district' => 408, 'name' => 'Tu Mơ Rông', 'id_province' => 34],
            
                        // Lai Châu
                        ['id_district' => 409, 'name' => 'Lai Châu', 'id_province' => 35],
                        ['id_district' => 410, 'name' => 'Mường Tè', 'id_province' => 35],
                        ['id_district' => 411, 'name' => 'Phong Thổ', 'id_province' => 35],
                        ['id_district' => 412, 'name' => 'Sìn Hồ', 'id_province' => 35],
                        ['id_district' => 413, 'name' => 'Tam Đường', 'id_province' => 35],
                        ['id_district' => 414, 'name' => 'Tân Uyên', 'id_province' => 35],
            
                        // Lâm Đồng
                        ['id_district' => 415, 'name' => 'Đà Lạt', 'id_province' => 36],
                        ['id_district' => 416, 'name' => 'Bảo Lâm', 'id_province' => 36],
                        ['id_district' => 417, 'name' => 'Bảo Lộc', 'id_province' => 36],
                        ['id_district' => 418, 'name' => 'Cát Tiên', 'id_province' => 36],
                        ['id_district' => 419, 'name' => 'Đạ Huoai', 'id_province' => 36],
                        ['id_district' => 420, 'name' => 'Đạ Tẻh', 'id_province' => 36],
                        ['id_district' => 421, 'name' => 'Đam Rông', 'id_province' => 36],
                        ['id_district' => 422, 'name' => 'Di Linh', 'id_province' => 36],
                        ['id_district' => 423, 'name' => 'Đơn Dương', 'id_province' => 36],
                        ['id_district' => 424, 'name' => 'Lạc Dương', 'id_province' => 36],
                        ['id_district' => 425, 'name' => 'Lâm Hà', 'id_province' => 36],
            
                        // Lạng Sơn
                        ['id_district' => 426, 'name' => 'Lạng Sơn', 'id_province' => 37],
                        ['id_district' => 427, 'name' => 'Bắc Sơn', 'id_province' => 37],
                        ['id_district' => 428, 'name' => 'Bình Gia', 'id_province' => 37],
                        ['id_district' => 429, 'name' => 'Cao Lộc', 'id_province' => 37],
                        ['id_district' => 430, 'name' => 'Chi Lăng', 'id_province' => 37],
                        ['id_district' => 431, 'name' => 'Đình Lập', 'id_province' => 37],
                        ['id_district' => 432, 'name' => 'Hữu Lũng', 'id_province' => 37],
                        ['id_district' => 433, 'name' => 'Lộc Bình', 'id_province' => 37],
                        ['id_district' => 434, 'name' => 'Tràng Định', 'id_province' => 37],
                        ['id_district' => 435, 'name' => 'Văn Lãng', 'id_province' => 37],
                        ['id_district' => 436, 'name' => 'Văn Quan', 'id_province' => 37],

                        // Lào Cai
                        ['id_district' => 437, 'name' => 'Lào Cai', 'id_province' => 38],
                        ['id_district' => 438, 'name' => 'Bắc Hà', 'id_province' => 38],
                        ['id_district' => 439, 'name' => 'Bảo Thắng', 'id_province' => 38],
                        ['id_district' => 440, 'name' => 'Bảo Yên', 'id_province' => 38],
                        ['id_district' => 441, 'name' => 'Bát Xát', 'id_province' => 38],
                        ['id_district' => 442, 'name' => 'Mường Khương', 'id_province' => 38],
                        ['id_district' => 443, 'name' => 'Sa Pa', 'id_province' => 38],
                        ['id_district' => 444, 'name' => 'Si Ma Cai', 'id_province' => 38],
                        ['id_district' => 445, 'name' => 'Văn Bàn', 'id_province' => 38],

                        // Long An
                        ['id_district' => 446, 'name' => 'Tân An', 'id_province' => 39],
                        ['id_district' => 447, 'name' => 'Bến Lức', 'id_province' => 39],
                        ['id_district' => 448, 'name' => 'Cần Đước', 'id_province' => 39],
                        ['id_district' => 449, 'name' => 'Cần Giuộc', 'id_province' => 39],
                        ['id_district' => 450, 'name' => 'Châu Thành', 'id_province' => 39],
                        ['id_district' => 451, 'name' => 'Đức Hòa', 'id_province' => 39],
                        ['id_district' => 452, 'name' => 'Đức Huệ', 'id_province' => 39],
                        ['id_district' => 453, 'name' => 'Mộc Hóa', 'id_province' => 39],
                        ['id_district' => 454, 'name' => 'Tân Hưng', 'id_province' => 39],
                        ['id_district' => 455, 'name' => 'Tân Thạnh', 'id_province' => 39],
                        ['id_district' => 456, 'name' => 'Tân Trụ', 'id_province' => 39],
                        ['id_district' => 457, 'name' => 'Thạnh Hóa', 'id_province' => 39],
                        ['id_district' => 458, 'name' => 'Thủ Thừa', 'id_province' => 39],
                        ['id_district' => 459, 'name' => 'Vĩnh Hưng', 'id_province' => 39],

                        // Nam Định
                        ['id_district' => 460, 'name' => 'Nam Định', 'id_province' => 40],
                        ['id_district' => 461, 'name' => 'Giao Thủy', 'id_province' => 40],
                        ['id_district' => 462, 'name' => 'Hải Hậu', 'id_province' => 40],
                        ['id_district' => 463, 'name' => 'Mỹ Lộc', 'id_province' => 40],
                        ['id_district' => 464, 'name' => 'Nam Trực', 'id_province' => 40],
                        ['id_district' => 465, 'name' => 'Nghĩa Hưng', 'id_province' => 40],
                        ['id_district' => 466, 'name' => 'Trực Ninh', 'id_province' => 40],
                        ['id_district' => 467, 'name' => 'Vụ Bản', 'id_province' => 40],
                        ['id_district' => 468, 'name' => 'Xuân Trường', 'id_province' => 40],
                        ['id_district' => 469, 'name' => 'Ý Yên', 'id_province' => 40],

                        // Ninh Bình
                        ['id_district' => 470, 'name' => 'Ninh Bình', 'id_province' => 42],
                        ['id_district' => 471, 'name' => 'Tam Điệp', 'id_province' => 42],
                        ['id_district' => 472, 'name' => 'Nho Quan', 'id_province' => 42],
                        ['id_district' => 473, 'name' => 'Gia Viễn', 'id_province' => 42],
                        ['id_district' => 474, 'name' => 'Hoa Lư', 'id_province' => 42],
                        ['id_district' => 475, 'name' => 'Yên Khánh', 'id_province' => 42],
                        ['id_district' => 476, 'name' => 'Kim Sơn', 'id_province' => 42],

                        // Ninh Thuận
                        ['id_district' => 477, 'name' => 'Phan Rang-Tháp Chàm', 'id_province' => 43],
                        ['id_district' => 478, 'name' => 'Bác Ái', 'id_province' => 43],
                        ['id_district' => 479, 'name' => 'Ninh Hải', 'id_province' => 43],
                        ['id_district' => 480, 'name' => 'Ninh Phước', 'id_province' => 43],
                        ['id_district' => 481, 'name' => 'Ninh Sơn', 'id_province' => 43],
                        ['id_district' => 482, 'name' => 'Thuận Bắc', 'id_province' => 43],
                        ['id_district' => 483, 'name' => 'Thuận Nam', 'id_province' => 43],

                        // Phú Thọ
                        ['id_district' => 484, 'name' => 'Việt Trì', 'id_province' => 44],
                        ['id_district' => 485, 'name' => 'Phú Thọ', 'id_province' => 44],
                        ['id_district' => 486, 'name' => 'Cẩm Khê', 'id_province' => 44],
                        ['id_district' => 487, 'name' => 'Đoan Hùng', 'id_province' => 44],
                        ['id_district' => 488, 'name' => 'Hạ Hòa', 'id_province' => 44],
                        ['id_district' => 489, 'name' => 'Lâm Thao', 'id_province' => 44],
                        ['id_district' => 490, 'name' => 'Phù Ninh', 'id_province' => 44],
                        ['id_district' => 491, 'name' => 'Tam Nông', 'id_province' => 44],
                        ['id_district' => 492, 'name' => 'Tân Sơn', 'id_province' => 44],
                        ['id_district' => 493, 'name' => 'Thanh Ba', 'id_province' => 44],
                        ['id_district' => 494, 'name' => 'Thanh Sơn', 'id_province' => 44],
                        ['id_district' => 495, 'name' => 'Thanh Thuỷ', 'id_province' => 44],
                        ['id_district' => 496, 'name' => 'Yên Lập', 'id_province' => 44],

                        // Quảng Bình
                        ['id_district' => 497, 'name' => 'Đồng Hới', 'id_province' => 45],
                        ['id_district' => 498, 'name' => 'Bố Trạch', 'id_province' => 45],
                        ['id_district' => 499, 'name' => 'Lệ Thủy', 'id_province' => 45],
                        ['id_district' => 500, 'name' => 'Minh Hóa', 'id_province' => 45],
                        ['id_district' => 501, 'name' => 'Quảng Ninh', 'id_province' => 45],
                        ['id_district' => 502, 'name' => 'Quảng Trạch', 'id_province' => 45],
                        ['id_district' => 503, 'name' => 'Tuyên Hóa', 'id_province' => 45],

                        // Quảng Nam
                        ['id_district' => 504, 'name' => 'Tam Kỳ', 'id_province' => 46],
                        ['id_district' => 505, 'name' => 'Hội An', 'id_province' => 46],
                        ['id_district' => 506, 'name' => 'Điện Bàn', 'id_province' => 46],
                        ['id_district' => 507, 'name' => 'Đại Lộc', 'id_province' => 46],
                        ['id_district' => 508, 'name' => 'Duy Xuyên', 'id_province' => 46],
                        ['id_district' => 509, 'name' => 'Quế Sơn', 'id_province' => 46],
                        ['id_district' => 510, 'name' => 'Nam Giang', 'id_province' => 46],
                        ['id_district' => 511, 'name' => 'Phước Sơn', 'id_province' => 46],
                        ['id_district' => 512, 'name' => 'Hiệp Đức', 'id_province' => 46],
                        ['id_district' => 513, 'name' => 'Thăng Bình', 'id_province' => 46],
                        ['id_district' => 514, 'name' => 'Núi Thành', 'id_province' => 46],
                        ['id_district' => 515, 'name' => 'Tiên Phước', 'id_province' => 46],

                        // Quảng Ngãi
                        ['id_district' => 516, 'name' => 'Quảng Ngãi', 'id_province' => 47],
                        ['id_district' => 517, 'name' => 'Bình Sơn', 'id_province' => 47],
                        ['id_district' => 518, 'name' => 'Ba Tơ', 'id_province' => 47],
                        ['id_district' => 519, 'name' => 'Đức Phổ', 'id_province' => 47],
                        ['id_district' => 520, 'name' => 'Lý Sơn', 'id_province' => 47],
                        ['id_district' => 521, 'name' => 'Minh Long', 'id_province' => 47],
                        ['id_district' => 522, 'name' => 'Mộ Đức', 'id_province' => 47],
                        ['id_district' => 523, 'name' => 'Nghĩa Hành', 'id_province' => 47],
                        ['id_district' => 524, 'name' => 'Sơn Hà', 'id_province' => 47],
                        ['id_district' => 525, 'name' => 'Sơn Tây', 'id_province' => 47],
                        ['id_district' => 526, 'name' => 'Sơn Tịnh', 'id_province' => 47],

                        // Quảng Ninh
                        ['id_district' => 527, 'name' => 'Hạ Long', 'id_province' => 48],
                        ['id_district' => 528, 'name' => 'Cẩm Phả', 'id_province' => 48],
                        ['id_district' => 529, 'name' => 'Móng Cái', 'id_province' => 48],
                        ['id_district' => 530, 'name' => 'Uông Bí', 'id_province' => 48],
                        ['id_district' => 531, 'name' => 'Đông Triều', 'id_province' => 48],
                        ['id_district' => 532, 'name' => 'Quảng Yên', 'id_province' => 48],
                        ['id_district' => 533, 'name' => 'Ba Chẽ', 'id_province' => 48],
                        ['id_district' => 534, 'name' => 'Bình Liêu', 'id_province' => 48],
                        ['id_district' => 535, 'name' => 'Cô Tô', 'id_province' => 48],
                        ['id_district' => 536, 'name' => 'Tiên Yên', 'id_province' => 48],
                        ['id_district' => 537, 'name' => 'Vân Đồn', 'id_province' => 48],

                        // Quảng Trị
                        ['id_district' => 538, 'name' => 'Đông Hà', 'id_province' => 49],
                        ['id_district' => 539, 'name' => 'Quảng Trị', 'id_province' => 49],
                        ['id_district' => 540, 'name' => 'Vĩnh Linh', 'id_province' => 49],
                        ['id_district' => 541, 'name' => 'Hải Lăng', 'id_province' => 49],
                        ['id_district' => 542, 'name' => 'Gio Linh', 'id_province' => 49],
                        ['id_district' => 543, 'name' => 'Cam Lộ', 'id_province' => 49],
                        ['id_district' => 544, 'name' => 'Triệu Phong', 'id_province' => 49],
                        ['id_district' => 545, 'name' => 'Hướng Hóa', 'id_province' => 49],
                        ['id_district' => 546, 'name' => 'Đakrông', 'id_province' => 49],
                        ['id_district' => 547, 'name' => 'Cồn Cỏ', 'id_province' => 49],

                        // Sóc Trăng
                        ['id_district' => 548, 'name' => 'Sóc Trăng', 'id_province' => 50],
                        ['id_district' => 549, 'name' => 'Châu Thành', 'id_province' => 50],
                        ['id_district' => 550, 'name' => 'Kế Sách', 'id_province' => 50],
                        ['id_district' => 551, 'name' => 'Mỹ Tú', 'id_province' => 50],
                        ['id_district' => 552, 'name' => 'Cù Lao Dung', 'id_province' => 50],
                        ['id_district' => 553, 'name' => 'Long Phú', 'id_province' => 50],
                        ['id_district' => 554, 'name' => 'Mỹ Xuyên', 'id_province' => 50],
                        ['id_district' => 555, 'name' => 'Ngã Năm', 'id_province' => 50],
                        ['id_district' => 556, 'name' => 'Thạnh Trị', 'id_province' => 50],
                        ['id_district' => 557, 'name' => 'Trần Đề', 'id_province' => 50],
                        ['id_district' => 558, 'name' => 'Vĩnh Châu', 'id_province' => 50],

                        // Sơn La
                        ['id_district' => 559, 'name' => 'Sơn La', 'id_province' => 51],
                        ['id_district' => 560, 'name' => 'Mường La', 'id_province' => 51],
                        ['id_district' => 561, 'name' => 'Quỳnh Nhai', 'id_province' => 51],
                        ['id_district' => 562, 'name' => 'Thuận Châu', 'id_province' => 51],
                        ['id_district' => 563, 'name' => 'Bắc Yên', 'id_province' => 51],
                        ['id_district' => 564, 'name' => 'Phù Yên', 'id_province' => 51],
                        ['id_district' => 565, 'name' => 'Mai Sơn', 'id_province' => 51],
                        ['id_district' => 566, 'name' => 'Yên Châu', 'id_province' => 51],
                        ['id_district' => 567, 'name' => 'Sông Mã', 'id_province' => 51],
                        ['id_district' => 568, 'name' => 'Mường Tè', 'id_province' => 51],
                        ['id_district' => 569, 'name' => 'Sốp Cộp', 'id_province' => 51],

                        // Tây Ninh
                        ['id_district' => 570, 'name' => 'Tây Ninh', 'id_province' => 52],
                        ['id_district' => 571, 'name' => 'Tân Biên', 'id_province' => 52],
                        ['id_district' => 572, 'name' => 'Tân Châu', 'id_province' => 52],
                        ['id_district' => 573, 'name' => 'Dương Minh Châu', 'id_province' => 52],
                        ['id_district' => 574, 'name' => 'Châu Thành', 'id_province' => 52],
                        ['id_district' => 575, 'name' => 'Hòa Thành', 'id_province' => 52],
                        ['id_district' => 576, 'name' => 'Gò Dầu', 'id_province' => 52],
                        ['id_district' => 577, 'name' => 'Bến Cầu', 'id_province' => 52],
                        ['id_district' => 578, 'name' => 'Trảng Bàng', 'id_province' => 52],

                        // Thái Bình
                        ['id_district' => 579, 'name' => 'Thái Bình', 'id_province' => 53],
                        ['id_district' => 580, 'name' => 'Quỳnh Phụ', 'id_province' => 53],
                        ['id_district' => 581, 'name' => 'Hưng Hà', 'id_province' => 53],
                        ['id_district' => 582, 'name' => 'Đông Hưng', 'id_province' => 53],
                        ['id_district' => 583, 'name' => 'Vũ Thư', 'id_province' => 53],
                        ['id_district' => 584, 'name' => 'Kiến Xương', 'id_province' => 53],
                        ['id_district' => 585, 'name' => 'Tiền Hải', 'id_province' => 53],

                        // Thái Nguyên
                        ['id_district' => 586, 'name' => 'Thái Nguyên', 'id_province' => 54],
                        ['id_district' => 587, 'name' => 'Sông Công', 'id_province' => 54],
                        ['id_district' => 588, 'name' => 'Định Hóa', 'id_province' => 54],
                        ['id_district' => 589, 'name' => 'Phú Lương', 'id_province' => 54],
                        ['id_district' => 590, 'name' => 'Đại Từ', 'id_province' => 54],
                        ['id_district' => 591, 'name' => 'Đồng Hỷ', 'id_province' => 54],
                        ['id_district' => 592, 'name' => 'Võ Nhai', 'id_province' => 54],

                        // Thừa Thiên Huế
                        ['id_district' => 593, 'name' => 'Huế', 'id_province' => 56],
                        ['id_district' => 594, 'name' => 'Phong Điền', 'id_province' => 56],
                        ['id_district' => 595, 'name' => 'Quảng Điền', 'id_province' => 56],
                        ['id_district' => 596, 'name' => 'Phú Vang', 'id_province' => 56],
                        ['id_district' => 597, 'name' => 'Hương Thủy', 'id_province' => 56],
                        ['id_district' => 598, 'name' => 'Hương Trà', 'id_province' => 56],
                        ['id_district' => 599, 'name' => 'A Lưới', 'id_province' => 56],
                        ['id_district' => 600, 'name' => 'Nam Đông', 'id_province' => 56],

                        // Tiền Giang
                        ['id_district' => 601, 'name' => 'Mỹ Tho', 'id_province' => 57],
                        ['id_district' => 602, 'name' => 'Cái Bè', 'id_province' => 57],
                        ['id_district' => 603, 'name' => 'Cai Lậy', 'id_province' => 57],
                        ['id_district' => 604, 'name' => 'Châu Thành', 'id_province' => 57],
                        ['id_district' => 605, 'name' => 'Gò Công', 'id_province' => 57],
                        ['id_district' => 606, 'name' => 'Gò Công Đông', 'id_province' => 57],
                        ['id_district' => 607, 'name' => 'Gò Công Tây', 'id_province' => 57],
                        ['id_district' => 608, 'name' => 'Tân Phước', 'id_province' => 57],
                        ['id_district' => 609, 'name' => 'Tân Phú Đông', 'id_province' => 57],
                        ['id_district' => 610, 'name' => 'Chợ Gạo', 'id_province' => 57],

                        // Trà Vinh
                        ['id_district' => 611, 'name' => 'Trà Vinh', 'id_province' => 58],
                        ['id_district' => 612, 'name' => 'Càng Long', 'id_province' => 58],
                        ['id_district' => 613, 'name' => 'Cầu Kè', 'id_province' => 58],
                        ['id_district' => 614, 'name' => 'Châu Thành', 'id_province' => 58],
                        ['id_district' => 615, 'name' => 'Duyên Hải', 'id_province' => 58],
                        ['id_district' => 616, 'name' => 'Tiểu Cần', 'id_province' => 58],
                        ['id_district' => 617, 'name' => 'Cầu Ngang', 'id_province' => 58],
                        ['id_district' => 618, 'name' => 'Trà Cú', 'id_province' => 58],
                    
                        // Tuyên Quang
                        ['id_district' => 619, 'name' => 'Tuyên Quang', 'id_province' => 59],
                        ['id_district' => 620, 'name' => 'Lâm Bình', 'id_province' => 59],
                        ['id_district' => 621, 'name' => 'Na Hang', 'id_province' => 59],
                        ['id_district' => 622, 'name' => 'Chiêm Hóa', 'id_province' => 59],
                        ['id_district' => 623, 'name' => 'Hàm Yên', 'id_province' => 59],
                        ['id_district' => 624, 'name' => 'Yên Sơn', 'id_province' => 59],
                        ['id_district' => 625, 'name' => 'Sơn Dương', 'id_province' => 59],

                        // Vĩnh Long
                        ['id_district' => 626, 'name' => 'Vĩnh Long', 'id_province' => 60],
                        ['id_district' => 627, 'name' => 'Long Hồ', 'id_province' => 60],
                        ['id_district' => 628, 'name' => 'Mang Thít', 'id_province' => 60],
                        ['id_district' => 629, 'name' => 'Vũng Liêm', 'id_province' => 60],
                        ['id_district' => 630, 'name' => 'Tam Bình', 'id_province' => 60],
                        ['id_district' => 631, 'name' => 'Bình Minh', 'id_province' => 60],

                        // Vĩnh Phúc
                        ['id_district' => 632, 'name' => 'Vĩnh Yên', 'id_province' => 61],
                        ['id_district' => 633, 'name' => 'Phúc Yên', 'id_province' => 61],
                        ['id_district' => 634, 'name' => 'Sông Lô', 'id_province' => 61],
                        ['id_district' => 635, 'name' => 'Tam Dương', 'id_province' => 61],
                        ['id_district' => 636, 'name' => 'Lập Thạch', 'id_province' => 61],
                        ['id_district' => 637, 'name' => 'Tam Đảo', 'id_province' => 61],
                        ['id_district' => 638, 'name' => 'Bình Xuyên', 'id_province' => 61],

                        // Yên Bái
                        ['id_district' => 639, 'name' => 'Yên Bái', 'id_province' => 62],
                        ['id_district' => 640, 'name' => 'Nghĩa Lộ', 'id_province' => 62],
                        ['id_district' => 641, 'name' => 'Lục Yên', 'id_province' => 62],
                        ['id_district' => 642, 'name' => 'Văn Yên', 'id_province' => 62],
                        ['id_district' => 643, 'name' => 'Mù Căng Chải', 'id_province' => 62],
                        ['id_district' => 644, 'name' => 'Trấn Yên', 'id_province' => 62],
                        ['id_district' => 645, 'name' => 'Văn Chấn', 'id_province' => 62],

                        // Phú Yên
                        ['id_district' => 646, 'name' => 'Tuy Hòa', 'id_province' => 63],
                        ['id_district' => 647, 'name' => 'Sông Cầu', 'id_province' => 63],
                        ['id_district' => 648, 'name' => 'Đồng Xuân', 'id_province' => 63],
                        ['id_district' => 649, 'name' => 'Sơn Hòa', 'id_province' => 63],
                        ['id_district' => 650, 'name' => 'Sông Hinh', 'id_province' => 63],
                        ['id_district' => 651, 'name' => 'Tây Hoà', 'id_province' => 63],
                        ['id_district' => 652, 'name' => 'Phú Hòa', 'id_province' => 63],
                        ['id_district' => 653, 'name' => 'Đông Hòa', 'id_province' => 63],

                        // Bà Rịa - Vũng Tàu (id_province: 7)
                        ['id_district' => 654, 'name' => 'Vũng Tàu', 'id_province' => 7],
                        ['id_district' => 655, 'name' => 'Bà Rịa', 'id_province' => 7],
                        ['id_district' => 656, 'name' => 'Châu Đức', 'id_province' => 7],
                        ['id_district' => 657, 'name' => 'Xuyên Mộc', 'id_province' => 7],
                        ['id_district' => 658, 'name' => 'Long Điền', 'id_province' => 7],
                        ['id_district' => 659, 'name' => 'Đất Đỏ', 'id_province' => 7],
                        ['id_district' => 660, 'name' => 'Tân Thành', 'id_province' => 7],
                        ['id_district' => 661, 'name' => 'Côn Đảo', 'id_province' => 7],

                        // Additional districts from various provinces
                        ['id_district' => 39, 'name' => 'Buôn Hồ', 'id_province' => 19],
                        ['id_district' => 255, 'name' => 'Điện Biên Đông', 'id_province' => 21],
                        ['id_district' => 257, 'name' => 'TP. Cao Lãnh', 'id_province' => 23],
                        ['id_district' => 360, 'name' => 'TP. Hồng Ngự', 'id_province' => 23],
                        ['id_district' => 662, 'name' => 'Sa Đéc', 'id_province' => 23],
                        ['id_district' => 663, 'name' => 'Chư Pưh', 'id_province' => 24],
                        ['id_district' => 664, 'name' => 'Đak Pơ', 'id_province' => 24],
                        ['id_district' => 665, 'name' => 'Đak Cơ', 'id_province' => 24],
                        ['id_district' => 666, 'name' => 'Phú Thiện', 'id_province' => 24],
                        ['id_district' => 667, 'name' => 'Thị xã Kỳ Anh', 'id_province' => 27],
                        ['id_district' => 668, 'name' => 'Bình Giang', 'id_province' => 28],
                        ['id_district' => 669, 'name' => 'Cẩm Giàng', 'id_province' => 28],
                        ['id_district' => 670, 'name' => 'Tứ Kỳ', 'id_province' => 28],
                        ['id_district' => 671, 'name' => 'Thị xã Long Mỹ', 'id_province' => 29],
                        ['id_district' => 672, 'name' => 'Vị Thủy', 'id_province' => 29],
                        ['id_district' => 673, 'name' => 'Hà Tiên', 'id_province' => 33],
                        ['id_district' => 674, 'name' => 'Kon Rẫy', 'id_province' => 34],
                        ['id_district' => 675, 'name' => 'Nậm Nhùn', 'id_province' => 35],
                        ['id_district' => 676, 'name' => 'Than Uyên', 'id_province' => 35],
                        ['id_district' => 677, 'name' => 'Đức Trọng', 'id_province' => 36],
                        ['id_district' => 678, 'name' => 'Kiến Tường', 'id_province' => 39],
                        ['id_district' => 679, 'name' => 'Hoàng Mai', 'id_province' => 41],
                        ['id_district' => 680, 'name' => 'Yên Mô', 'id_province' => 42],
                        ['id_district' => 681, 'name' => 'Ba Đồn', 'id_province' => 45],
                        ['id_district' => 682, 'name' => 'Bắc Trà My', 'id_province' => 46],
                        ['id_district' => 683, 'name' => 'Đông Giang', 'id_province' => 46],
                        ['id_district' => 684, 'name' => 'Nam Trà My', 'id_province' => 46],
                        ['id_district' => 685, 'name' => 'Nông Sơn', 'id_province' => 46],
                        ['id_district' => 686, 'name' => 'Phú Ninh', 'id_province' => 46],
                        ['id_district' => 687, 'name' => 'Tây Giang', 'id_province' => 46],
                        ['id_district' => 688, 'name' => 'Trà Bồng', 'id_province' => 47],
                        ['id_district' => 689, 'name' => 'Tư Nghĩa', 'id_province' => 47],
                        ['id_district' => 690, 'name' => 'Đầm Hà', 'id_province' => 48],
                        ['id_district' => 691, 'name' => 'Hải Hà', 'id_province' => 48],
                        ['id_district' => 692, 'name' => 'Mộc Châu', 'id_province' => 51],
                        ['id_district' => 693, 'name' => 'Thái Thụy', 'id_province' => 53],
                        ['id_district' => 694, 'name' => 'Phổ Yên', 'id_province' => 54],
                        ['id_district' => 695, 'name' => 'Phú Bình', 'id_province' => 54],
                        ['id_district' => 696, 'name' => 'Phú Lộc', 'id_province' => 56],
                        ['id_district' => 697, 'name' => 'Thị xã Cai Lậy', 'id_province' => 57],
                        ['id_district' => 698, 'name' => 'Thị xã Duyên Hải', 'id_province' => 58],
                        ['id_district' => 699, 'name' => 'Bình Tân', 'id_province' => 60],
                        ['id_district' => 700, 'name' => 'Trà Ôn', 'id_province' => 60],
                        ['id_district' => 701, 'name' => 'Vĩnh Tường', 'id_province' => 61],
                        ['id_district' => 702, 'name' => 'Yên Lạc', 'id_province' => 61],
                        ['id_district' => 703, 'name' => 'Yên Bình', 'id_province' => 62],
                        ['id_district' => 704, 'name' => 'Trạm Tấu', 'id_province' => 62],
                        ['id_district' => 705, 'name' => 'Tuy An', 'id_province' => 63],
        ]);
    }
}
